# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yellow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 450)
        MainWindow.setStyleSheet("background-color: rgb(249, 244, 120);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_color = QtWidgets.QLabel(self.centralwidget)
        self.lb_color.setGeometry(QtCore.QRect(90, 120, 621, 121))
        font = QtGui.QFont()
        font.setPointSize(49)
        font.setBold(True)
        font.setWeight(75)
        self.lb_color.setFont(font)
        self.lb_color.setTextFormat(QtCore.Qt.AutoText)
        self.lb_color.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_color.setObjectName("lb_color")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(700, 410, 89, 25))
        self.btn_back.setObjectName("btn_back")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb_color.setText(_translate("MainWindow", "YELLOW"))
        self.btn_back.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
